### ISSUE TITLE
Generate server key

### ISSUE THREAD

**Issue by nickpetrovic** [mikemackintosh/ruby-easyrsa#7]
In regards to openvpn, how do I create a server-only key?

From what I understand, the server keys have a different extension than the client keys. Here's some info on that: http://serverfault.com/questions/307196/should-build-key-server-be-used-with-openvpn. (nsCertType=server)

Here's the openvpn documentation on it: https://openvpn.net/index.php/open-source/documentation/howto.html#pki

I'm by no means a ruby expert, but it seems that some additional code may be needed to allow modification of the certificate extensions. Any help or clarification would be greatly appreciated.

**Comment by mikemackintosh** [comment]
Late to the party and my Ruby's kinda rusty now, but https://github.com/mikemackintosh/ruby-easyrsa/commit/3fab650f5e615412a4bd813d24b555d41661e340 should take care of it now
